{{- if .Values.autologgerServiceAndDeployment.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "auto-logger-helm.serviceAccountName" . }}
  labels:
{{ include "auto-logger-helm.labels" . | nindent 4 }}
{{- end -}}
