apiVersion: v1
kind: Service
metadata:
  name: {{ include "auto-logger-helm.fullname" . }}
  labels:
    {{- include "auto-logger-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.autologgerServiceAndDeployment.service.type }}
  ports:
    - port: {{ .Values.autologgerServiceAndDeployment.service.port }}
      targetPort: {{ .Values.autologgerServiceAndDeployment.service.port }}
      protocol: TCP
      name: http
      nodePort: 32001
  selector:
    {{- include "auto-logger-helm.selectorLabels" . | nindent 4 }}
